### ISSUE TITLE
Enhancement of Maintenance Panel

### ISSUE THREAD

**Issue by RameswariMohanty** [RameswariMohanty/VMCS#1]
@shivauzumaki -A new Enhancement request has come up. As per the enhancement request the system will provide an at-a-glance display of the cash amount available , by denomination, for collection by the Maintainer. Please do a impact analysis and let me know the results.

**Comment by shivauzumaki** [comment]
@RameswariMohanty Maintenance and Store modules are affected by the enhancement request. A defect has also been identified in the Maintenance module. Please take necessary actions.
[DesignModelReport.docx](https://github.com/RameswariMohanty/VMCS/files/486933/DesignModelReport.docx)

**Comment by RameswariMohanty** [comment]
@vishnusr90 - As per the user request a new enhancement is proposed. Please go through the Analyst's impact analysis report and go ahead with implementing the changes.

**Comment by vishnusr90** [comment]
@madLifeZPC  Please work on the enhancement by referring to the updated DesignModelReport. A new branch (enhancement) has been created for the same.

**Comment by madLifeZPC** [comment]
@vishnusr90  - Enhancement finished, please check and proceed for testing.

**Comment by vishnusr90** [comment]
@Vrinda1402 Enhancements has been added to the system. Please start the testing.

**Comment by Vrinda1402** [comment]
@vishnusr90 Enhancement tested successfully. Code working as per the requirements. No defects found.

**Comment by vishnusr90** [comment]
@vigneshtrigonometry  Please create the pull request and proceed with the release.

**Comment by vishnusr90** [comment]
@madLifeZPC Please create the pull request and proceed with the release.

**Comment by madLifeZPC** [comment]
@pramodkamath - Pull request created, please check and merge it.

**Comment by pramodkamath** [comment]
Merged Enhancement. Handing back to Tech Lead @vishnusr90

**Comment by vishnusr90** [comment]
@zzis  The enhancement has been included into the system. Kindly perform the UAT.

**Comment by zzis** [comment]
@vishnusr90 No defects were found, the enhancement is accepted, UAT is approved.

**Comment by vishnusr90** [comment]
@pramodkamath  UAT has been approved. Kindly proceed with the release.

**Comment by pramodkamath** [comment]
Incorporated into latest Release. Please close the Issues.

**Comment by RameswariMohanty** [comment]
Enhancement is implemented. So Closed
