### ISSUE TITLE
Defect in the values on completion of a maintenance session

### ISSUE THREAD

**Issue by RameswariMohanty** [RameswariMohanty/VMCS#2]
@puja3001 - During the enhancement analysis we found a severity 2 defect in maintenance module. Please analyse the defect and let me know the results.

**Comment by puja3001** [comment]
@RameswariMohanty - The following defect is identified- The values for "Show Total Cash Held" and "Press to Collect Cash" is not reset to null after execution of "Press Here When Finished" (on completion of maintenance session). As a result of which, the cash previously held and collected, persists in display on completion of Maintenance session.
After review and analysis, there is only one module found to be affected- Maintenance, in the process of fixing it.

**Comment by RameswariMohanty** [comment]
@vishnusr90  - As per the Puja's analysis of the defect , Please fix the defect.

**Comment by vishnusr90** [comment]
@vigneshtrigonometry Please start resolving the defect referring to the analyst's comments. A new  branch (defectFixing) has been created.

**Comment by vigneshtrigonometry** [comment]
@vishnusr90 

The defects addressed by the analyst have been fixed.

You may proceed to test.

**Comment by vishnusr90** [comment]
@Vrinda1402  A defect in the maintenance session has been resolved by the developer. Please start the testing.

**Comment by Vrinda1402** [comment]
@vishnusr90 Defect tested successfully. Issue has been resolved as per requirement.

**Comment by vishnusr90** [comment]
@vigneshtrigonometry  Please create the pull request and proceed with the release.

**Comment by vigneshtrigonometry** [comment]
@pramodkamath 

Pull request created for the Release manager.

**Comment by pramodkamath** [comment]
Merged Defect fixes. Handing issue back to Tech Lead. @vishnusr90

**Comment by vishnusr90** [comment]
@issguoqi  The defect has be fixed and tested properly. Kindly perform the UAT.

**Comment by issguoqi** [comment]
@vishnusr90 The defects have been fixed, and UAT is approved.

**Comment by vishnusr90** [comment]
@pramodkamath UAT has been approved. Kindly proceed with the release.

**Comment by pramodkamath** [comment]
Incorporated into latest Release. Please close the Issues.

**Comment by RameswariMohanty** [comment]
Defect is fixed . So closed.
